[package]
name = "wizards_castle_ncurses"
version = "0.1.0"
authors = ["Brian \"Beej Jorgensen\" Hall <beej@beej.us>"]
edition = "2018"

[dependencies]
wizardscastle = { git = "https://github.com/beejjorgensen/Wizards-Castle-Rust" }
ncurses = "5.98.0"